name: CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Tests (Python 3.11)
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Ensure pytest is present even if not listed
          pip install -r requirements.txt pytest

      - name: Show environment
        run: |
          python --version
          pip list

      - name: Prepare database (migrate + seed)
        run: |
          python -m scripts.migrate
          python -m scripts.seed

      - name: Run tests
        run: pytest -q tests/

  lint:
    name: Ruff Lint (bonus)
    runs-on: ubuntu-latest
    # Non-blocking; job will always be marked successful
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        # --exit-zero ensures success even if there are violations
        run: ruff check --exit-zero --output-format=github .
